# Generated by Django 3.0.4 on 2020-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200323_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
